package triangleNumDiv;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers. 
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 * 
 * @author st477134
 *
 */
public class TriangleNumDiv {
	
	public TriangleNumDiv(){ }
	
	public static void main(String [] args){
		TriangleNumDiv tnd = new TriangleNumDiv();
		tnd.run();
	}
	
	public void run(){
		
		int triangle = 1;
		int nextNum = 2;
		int numDiv = 0;
		
		try{
			while(true){
				
				for(int i = 1; i <= triangle/2; i++){
					if(triangle % i == 0){
						numDiv++;
						if(numDiv == 500){ //+1 for the number itself
							throw new Exception("Done!");
						}
					}
				}
				numDiv = 0;
				triangle += nextNum;
				nextNum++;
			}
		}catch(Exception e){ }
		
		System.out.println(triangle);
		
	}

}
